# Generated by Django 2.2.11 on 2020-03-24 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_awarenessdatamodel_indiametamodel_selfcheckupmodel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='awarenessdatamodel',
            unique_together={('link', 'title')},
        ),
    ]
