# Generated by Django 2.2.11 on 2020-03-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_awarenessdatamodel_indiametamodel_selfcheckupmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfcheckupmodel',
            name='ip',
            field=models.GenericIPAddressField(),
        ),
    ]
