# Generated by Django 2.2.11 on 2020-03-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200324_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfcheckupmodel',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
