# Generated by Django 2.2.11 on 2020-03-25 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_selfcheckupmodel_age'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='selfcheckupmodel',
            unique_together={('ip', 'age')},
        ),
    ]
